### ISSUE TITLE
`Object.isAbstractMap()`?

### ISSUE THREAD

**Issue by hax** [Agoric/proposal-readonly-collections#3]
If no AbstractMap in prototype chain which means no `o instanceof AbstractMap`, maybe we need `Object.isAbstractMap(o)`?

**Comment by erights** [comment]
I would not put this on `Object`, but perhaps something like this elsewhere.

At the tc39 meeting, @ljharb suggested that inserting an `AbtractMap.prototype` between `Map.prototype` and `Object.prototype` may be adequately compatible to be attempted. @ljharb suggested that we leave all on `Map.prototype` all methods currently there, but also duplicate the query methods onto `AbstractMap.prototype`. 

We would need to attempt this on all relevant collections and either do all or none. I don't know how we'd test the web compatibility of this suggestion. But if we can determine it to be compat enough, I find it attractive.

**Comment by ljharb** [comment]
I'll research how all the popular shims interact with collections and their prototypes over the coming weeks, which will hopefully make either an objective case that it's not web compatible, or a compelling enough case that it is likely to be to convince browsers to ship it.

It could even, perhaps, be shipped asap without exposing a global `AbstractMap` as a needs consensus PR, separate from this proposal, if the committee feels that this would be worth it.

**Comment by hax** [comment]
It seems no reason to intentionally rely on `Map.prototype.__proto__ === Object.prototype`, so I am optimistic about adding AbstractMap.prototype. 😃 

So I close this issue now. Could reopen if we do not have the fortune.
